<a href="https://colab.research.google.com/github/jayesh68088/AI-CLUB/blob/main/numpy/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY IN DIFFERENT WAYS***

In [1]:
import numpy as np

**lists**

In [2]:
PythonList = [1,2,4,3]
print(PythonList)


[1, 2, 4, 3]


**NUMPY**

In [3]:
numpy_array = np.array(PythonList)
numpy_array

array([1, 2, 4, 3])

In [4]:
a = numpy_array+10
print(a)

[11 12 14 13]


In [5]:
a = np.array([2,6,8])
print(a)

[2 6 8]


In [6]:
b = a +10
print(b)

[12 16 18]


In [7]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [8]:
c = np.array([(3,2,5,6),
              (2,9,7,1)])
print(c)

[[3 2 5 6]
 [2 9 7 1]]


In [9]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


**TO PRINT 3 ROWS 3 COULMNS OF ZEROS**

In [10]:
x=np.zeros((3,3), dtype=np.int16)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


**TO PRINT 3 TIMES OF 2 ROWS 4 COLUMNS OF ONES**

In [ ]:
y=np.ones((3,2,4), dtype=np.int16)
print(y)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


**RESHAPE TO 1 ELEMENT LISTS**

In [ ]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(6,1)

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
print(e)

[[1 2 3]
 [4 5 6]]


In [ ]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
print('Second column:', e[:,1])

Second column: [2 5]


In [ ]:
print(e[1, :2])

[4 5]


In [ ]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

**HORITONTAL AND VERTICAL STACK**

In [11]:
f = np.array([2,4,3])
g = np.array([7,9,6])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [2 4 3 7 9 6]
Vertical append:
[[2 4 3]
 [7 9 6]]


**TO FIND A LIST OF RANDOM ELEMENTS**

In [12]:
normal_array = np.random.normal(4, 0.4, 8)
print(normal_array)

[3.84531148 3.94764533 4.0084207  4.67408361 3.91686547 3.52031277
 4.52741423 3.75705634]


**FIND MIN , MAX, MEAN, MEDIAN,STD FROM A LISTS**

In [13]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

3.520312768113297
4.6740836138356086
4.024638742538492
3.932255399897478
0.3623657028585927


**TO PRINT ELEMENTS IN RANGE**

In [14]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [15]:
np.arange(3, 10,6)

array([3, 9])

In [16]:
np.linspace(2.0, 8.0, num=20)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

In [17]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [18]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [19]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

**TO FIND DOT PRODUCT OF MATRIX**

In [22]:
f = np.array([4,5,6])
g = np.array([1,5,2])
np.dot(f, g)

41

**TO FIND THE INVERSE OF MATRIX**

In [23]:
A = np.array([[1, 2, 5],
              [3, -5, 4],
              [1, 4, 6]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[-4.18181818  0.72727273  3.        ]
 [-1.27272727  0.09090909  1.        ]
 [ 1.54545455 -0.18181818 -1.        ]]


**TO FIND THE MATRIX MULTIPLICATION**

In [ ]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

**TO FIND THE DETERMINANT OF MATRIX**

In [ ]:
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


**TO FIND THE RANK OF MATRIX**

In [ ]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

**TO FIND THE TRANSPOSE OF THE MATRIX**

In [ ]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


**TO FIND THE TRACE OF MATRIX**

In [26]:
gfg = np.matrix('[2, 3; 10, 6]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[8]]


**TO FIND THE EIGEN VALUES AND EIGEN VECTORS OF MATRIX**

In [27]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]
